# Generated by Django 3.0.7 on 2020-06-28 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='programmingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Python'), ('C', 'C++'), ('J', 'Java'), ('c', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_slug', models.SlugField(unique=True)),
                ('code', models.TextField(max_length=10000)),
                ('problems', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Problem.problem')),
                ('programming_language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Judge.programmingLanguage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('A', 'Accepted'), ('WA', 'Wrong Answer'), ('C', 'Compilation Error'), ('S', 'Segmentation Fault')], max_length=2)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='submissionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.CharField(choices=[('P', 'Passed'), ('F', 'Failed')], max_length=1)),
                ('submission_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Judge.submission')),
                ('testcase_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Problem.testCase')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Judge.verdict'),
        ),
    ]
