# Generated by Django 3.0.7 on 2020-06-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0002_auto_20200623_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Detail', 'verbose_name_plural': 'User Details'},
        ),
    ]
